# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


In [13]:
s = "Hi there Sam!"
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [16]:
planet = "Earth"
diameter = 12742

In [15]:
s="The diameter of Earth is {diameter:} kilometers."
print(s.format(diameter = 12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [18]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
import numpy as np
array=np.zeros(10)
print("An Array of 10 zeros:")
print(array)

An Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd
data = [10,20,30]
df = pd.DataFrame(data,columns=[''])
print(df)


     
0  10
1  20
2  30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [33]:
import datetime
import pandas as pd
start = datetime.datetime.strptime("01-01-2021", "%d-%m-%Y")
end = datetime.datetime.strptime("10-02-2021", "%d-%m-%Y")
dategenerated = pd.date_range(start, end)
print (dategenerated.strftime("%d-%m-%Y"))

Index(['01-01-2021', '02-01-2021', '03-01-2021', '04-01-2021', '05-01-2021',
       '06-01-2021', '07-01-2021', '08-01-2021', '09-01-2021', '10-01-2021',
       '11-01-2021', '12-01-2021', '13-01-2021', '14-01-2021', '15-01-2021',
       '16-01-2021', '17-01-2021', '18-01-2021', '19-01-2021', '20-01-2021',
       '21-01-2021', '22-01-2021', '23-01-2021', '24-01-2021', '25-01-2021',
       '26-01-2021', '27-01-2021', '28-01-2021', '29-01-2021', '30-01-2021',
       '31-01-2021', '01-02-2021', '02-02-2021', '03-02-2021', '04-02-2021',
       '05-02-2021', '06-02-2021', '07-02-2021', '08-02-2021', '09-02-2021',
       '10-02-2021'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [35]:
import pandas as pd
data = [['aaa',22],['bbb',25],['ccc',24]]
df = pd.DataFrame(data,columns =['Name','Age'])
print(df)

  Name  Age
0  aaa   22
1  bbb   25
2  ccc   24
